# Site settings
title:       the cdcd
email:       your_email@example.com
author:      cdcd
description: "things I work on in my spare time"
baseurl:     ""
url:         "https://thecdcd.github.io"

# Google analytics
# google_analytics: SOMEIDHERE

# Disqus post comments
# (leave blank to disable Disqus)
# disqus: disqus-id

# Social icons
github_username: "thecdcd"
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: ''
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# GitHub
github_repo: thecdcd/thecdcd.github.io

# Syntax highlighting
#highlighter: pygments

excerpt_separator: "<!-- more -->"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
